export const navName = {
    login: 'Login',
    register: 'Register',
    forgetPassword: 'Forget Password',
    main: 'Main',
    home: 'Home',
    download: 'Download',
    browse: 'Browse',
    search: 'Search',
    profile: 'Profile',
    newRelease: 'New',
    skill: 'Skill',
    topic: 'Topic',
    path: 'Path',
    author: 'Author',
}